### ISSUE TITLE
api-visualizer is not working with mitmproxy 7.x.x

### ISSUE THREAD

**Issue by rishubil** [Cryolite/mahjongsoul_sniffer#40]
It works normally if you explicitly specify the mitmproxy version as 6.0.2 in `api-visualizer/web-server.Dockerfile`

Please refer to the contents of the document below.

https://docs.mitmproxy.org/stable/api/mitmproxy/websocket.html

**Comment by Cryolite** [comment]
Confirmed.
The root cause of this issue is a change in the WebSocket APIs in mitmproxy 7.x.x.
The issue has been fixed in the branch `fix/issue40`. Could you try it?

**Comment by rishubil** [comment]
I just tested it and it's working normally. Thank you.

**Comment by Cryolite** [comment]
The fix has been merged into the `master` branch. Thank you for the bug report and fix confirmation.
