### ISSUE TITLE
Does game-abstract-crawler still work?

### ISSUE THREAD

**Issue by GrandDuke1106** [Cryolite/mahjongsoul_sniffer#88]
I followed the instructions to run docker. 
And I set the mitmproxy version to 7.0.3 to avoid the "Descriptors cannot not be created directly." error.

Although docker ran successfully in the end, there were no more records in s3.

**Comment by GrandDuke1106** [comment]
Here it is

# Screenshots

![00-ページ読み込み](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/645f2ee7-94c1-4cfc-8765-1be64ca5b7cb)

# Sniffer

![image](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/99cf571d-5454-44e2-a544-77ea7d86d234)

# Archiver

![image](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/5fc6c3a0-5b59-4258-84e7-800710ab6cce)

# Crawler

![image](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/f9b904d3-c23d-4a04-a08d-1f4ba40066e8)

**Comment by gavingrey** [comment]
I am currently encountering this exact same issue.

**Comment by xzdlj** [comment]
Try to use version 4.2.0 selenium.
The usage of **MoveToElementOffsetOrigin** was changed in 4.3 version.  [https://github.com/SeleniumHQ/selenium/commit/cb68cf53b2306a4e5d524e789442c0df4f3deda9](url)

**Comment by GrandDuke1106** [comment]
@xzdlj Thank you very much. It works!

But now there is a new problem. Can you help me

![image](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/639725c6-506c-4c1f-878d-47f1c6c9213a)

**Comment by xzdlj** [comment]
> @xzdlj Thank you very much. It works!
> 
> But now there is a new problem. Can you help me
> 
> ![image](https://user-images.githubusercontent.com/98164810/258769274-639725c6-506c-4c1f-878d-47f1c6c9213a.png)

Please post the **Screenshots** from the monitor webpage.

**Comment by GrandDuke1106** [comment]
@xzdlj Thank you very much. Here are Screenshots

I feel that the program may not be able to read the verification code in s3.

![00-ページ読み込み](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/583bf451-c624-46ad-8b07-da51e9651c9e)

![01-ログインボタンクリック](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/ccfbac82-0212-4e95-a7be-1780dc44277f)

![02-メールアドレス入力](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/d0eb547a-4767-413b-bdf1-4a32cbee2f6b)

![03-コードを受け取るボタンクリック](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/d8d0d804-b6a1-41e5-bae8-13ab3b78cb8d)

![04-確認ボタンクリック](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/d787e038-ce82-4989-a9de-c94438269c84)

![99-エラー](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/d4e6a9d3-3c24-45e2-b81a-24494a66eef1)

**Comment by xzdlj** [comment]
> I feel that the program may not be able to read the verification code in s3.
> 
I agree with you.

Try to restart the crawler container and then check whether there is the verification email in s3 bucket.(Restart may work somehow)
If you find the email in the right place, change the **logging level** in **config.yaml** to **DEBUG** for more information.
Otherwise, check your s3 configuration.

**Comment by GrandDuke1106** [comment]
@xzdlj 
I analyzed the log and found that the verification code could not be obtained because the sender of the email could not be matched. 

On line 69 of the ```mahjongsoul_sniffer/mahjongsoul_sniffer
/yostar_login.py```  file, I changed ```passport@mail.yostar.co.jp``` to ```info@passport.yostar.co.jp``` . After this, I was able to log in successfully.

![image](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/33476ee6-065d-4f3c-970f-7c9fe248d466)

Thanks for your help.

**Comment by GrandDuke1106** [comment]
This issue has been solved.

**Comment by Cryolite** [comment]
As pointed out by xzdlj in the comment https://github.com/Cryolite/mahjongsoul_sniffer/issues/88#issuecomment-1667129999, the API specifications have changed in Selenium 4.3. I committed the change addressing this issue to `develop` branch, which will soon be merged into `master` branch. If using Selenium 4.2 or earlier, revert the change made by the commit https://github.com/Cryolite/mahjongsoul_sniffer/commit/960bc0043d04b36b21e4fd5cf73cbfd63666ca0b.

**Comment by GrandDuke1106** [comment]
> As pointed out by xzdlj in the comment [#88 (comment)](https://github.com/Cryolite/mahjongsoul_sniffer/issues/88#issuecomment-1667129999), the API specifications have changed in Selenium 4.3. I committed the change addressing this issue to `develop` branch, which will soon be merged into `master` branch. If using Selenium 4.2 or earlier, revert the change made by the commit [960bc00](https://github.com/Cryolite/mahjongsoul_sniffer/commit/960bc0043d04b36b21e4fd5cf73cbfd63666ca0b).

Thank you for your update
